#!/bin/bash -e
################################################################
#
#  Name: Best Practices Checker
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/best-practices.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  Runs comprehensive Rust code quality checks including formatting, linting, documentation, and security analysis
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################


# Set standard directory variables and source all functions
SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
for FUNC in "$SCRIPTS_DIR/functions"/*.sh; do source "$FUNC"; done
PROJECT_DIR=$(get_project_dir)

echo "Running Rust Best Practices Check"
echo "================================="

# Ask user for build type
echo "Select build type:"
echo "1) Debug"
echo "2) Release"

# Check for command line arguments or non-interactive mode
if [[ "$1" == "--debug" ]] || [[ -n "$CI" ]] || [[ ! -t 0 ]]; then
    CHOICE=1
elif [[ "$1" == "--release" ]]; then
    CHOICE=2
else
    read -p "Enter choice (1 or 2): " CHOICE
fi

case $CHOICE in
    1)
        BUILD_TYPE="debug"
        BUILD_FLAG=""
        ;;
    2)
        BUILD_TYPE="release"
        BUILD_FLAG="--release"
        ;;
    *)
        echo "Invalid choice. Defaulting to Debug."
        BUILD_TYPE="debug"
        BUILD_FLAG=""
        ;;
esac

echo "Using $BUILD_TYPE build..."

# Read directory paths from config file
# Find config file
PROJECT_NAME=$(get_project_name)
CONFIG_FILE=$(get_config_file "$PROJECT_NAME" "$BUILD_TYPE")

# Check project type first
PROJECT_DIR=$(cargo locate-project --workspace --message-format=plain | xargs dirname)

# Check if this is a library project and adjust accordingly
if grep -q "^\[lib\]" "$PROJECT_DIR/Cargo.toml" && ! grep -q "^\[\[bin\]\]" "$PROJECT_DIR/Cargo.toml"; then
    # This is a library project
    if ! grep -q "^\[lib\]" "$PROJECT_DIR/Cargo.toml"; then
        INSTALL_DIR=$(get_install_directory "$BUILD_TYPE")
    fi
    CONFIG_DIR="/etc/rust-service"
    LOG_FILE_PATH="/var/log/rust-service"
    # Get binary name from lib config or Cargo.toml
    LIB_NAME=$(read_config_value "LIB_NAME" "$CONFIG_FILE")
    BINARY_NAME="$LIB_NAME"
else
    # This is a service project
    if ! grep -q "^\[lib\]" "$PROJECT_DIR/Cargo.toml"; then
        INSTALL_DIR=$(get_install_directory "$BUILD_TYPE")
    fi
    CONFIG_DIR=$(read_config_value "CONFIG_DIR" "$CONFIG_FILE")
    LOG_FILE_PATH=$(read_config_value "LOG_FILE_PATH" "$CONFIG_FILE")
fi

# Exit on any error
set -e

# Get binary name from config file (same as install.sh)
if [[ -z "$BINARY_NAME" ]]; then
# Get project name
PROJECT_NAME=$(get_project_name)
    # Set binary name based on project type
    if [[ -f "$PROJECT_DIR/config/service.toml" ]] || [[ "$CONFIG_FILE" == *"service.toml" ]]; then
        BINARY_NAME="$PROJECT_NAME"
    # Finally fall back to lib config
    else
        if [[ -f "$PROJECT_DIR/config/service.toml" ]]; then
            LIB_NAME=$(read_config_value "LIB_NAME" "$PROJECT_DIR/config/service.toml")
        fi
        BINARY_NAME="$LIB_NAME"
    fi
fi

echo "1. Code formatting check..."
cargo fmt --check

echo "2. Clippy linting (all levels) - DENY ALL WARNINGS except naming..."
cargo clippy --all-targets --all-features -- -D warnings -W clippy::all -W clippy::pedantic -W clippy::nursery -A non_snake_case -A clippy::upper_case_acronyms

echo "3. Documentation generation..."
RUSTDOCFLAGS="-D warnings -A non_snake_case -A clippy::upper_case_acronyms" cargo doc --no-deps --document-private-items

echo "4. Dead code detection - DENY ALL WARNINGS except naming..."
RUSTFLAGS="-D warnings -A non_snake_case -A clippy::upper_case_acronyms" cargo check

echo "5. Dependency tree analysis..."
cargo tree --duplicates

echo "6. Binary size analysis..."
# Check project type using Cargo.toml
if grep -q "^\[lib\]" "$PROJECT_DIR/Cargo.toml" && ! grep -q "^\[\[bin\]\]" "$PROJECT_DIR/Cargo.toml"; then
    # We're in a library project that doesn't produce binaries
    echo "Skipping binary size analysis for library project"
elif grep -q "^\[\[bin\]\]" "$PROJECT_DIR/Cargo.toml"; then
    # We're in a service project, build and check its binary
    RUSTFLAGS="-D warnings -A non_snake_case -A clippy::upper_case_acronyms" cargo build $BUILD_FLAG
    SERVICE_BINARY="$PROJECT_NAME"
    ls -lh target/$BUILD_TYPE/$SERVICE_BINARY
else
    # Default behavior for other cases
    RUSTFLAGS="-D warnings -A non_snake_case -A clippy::upper_case_acronyms" cargo build $BUILD_FLAG
    ls -lh target/$BUILD_TYPE/$BINARY_NAME
fi

echo "7. Architecture-specific check..."
CURRENT_ARCH=$(rustc --version --verbose | grep host | cut -d' ' -f2)
echo "Running checks for current architecture: $CURRENT_ARCH"
RUSTFLAGS="-D warnings -A non_snake_case -A clippy::upper_case_acronyms" cargo check --target $CURRENT_ARCH

echo "8. License compliance check..."
cargo license || echo "Warning: cargo license not installed"

echo "9. Cargo.toml validation..."
cargo verify-project

echo "10. Test coverage analysis..."
cargo tarpaulin --out Stdout || echo "Warning: cargo tarpaulin not installed"

echo "11. Memory safety checks..."
echo -e "${RED}⚠️  WARNING: miri checks SKIPPED to avoid downloading components${NC}"
echo -e "${RED}   Memory safety checks will be SKIPPED${NC}"
echo -e "${RED}   Run manually with: cargo +nightly miri test${NC}"

echo "All essential best practices checks completed successfully!"
