#!/bin/bash -e
################################################################
#
#  Name: Run Script
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/run.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  Runs the installed Rust service with proper user permissions and configuration validation
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################

set -e

# Set standard directory variables and source all functions
if [ -z "$SCRIPT_DIR" ]; then
    SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
fi
for FUNC in "$SCRIPT_DIR/functions"/*.sh; do source "$FUNC"; done
PROJECT_DIR=$(get_project_dir)

# Define configuration constants
DEBUG_CHOICE=1
RELEASE_CHOICE=2
ERROR_EXIT=1
CONFIG_FILE_PERMISSIONS=644

echo "Select binary type to run:"
echo "1) Debug"
echo "2) Release"
read -p "Enter choice (1 or 2): " CHOICE

case $CHOICE in
    1)
        DEBUG_SUFFIX="-debug"
        BUILD_TYPE="debug"
        ;;
    2)
        DEBUG_SUFFIX=""
        BUILD_TYPE="release"
        ;;
    *)
        echo "Invalid choice. Please enter 1 or 2."
        exit $ERROR_EXIT
        ;;
esac

# Find config file
PROJECT_NAME=$(get_project_name)
CONFIG_FILE=$(get_config_file "$PROJECT_NAME" "$BUILD_TYPE")

# Get project name
PROJECT_NAME=$(get_project_name)

# Get current architecture
CURRENT_ARCH=$(rustc --version --verbose | grep host | cut -d' ' -f2)

# Check if binary exists, if not build it
BINARY_PATH="target/$CURRENT_ARCH/$BUILD_TYPE/$PROJECT_NAME"
if [[ ! -f "$BINARY_PATH" ]]; then
    echo "Binary not found at $BINARY_PATH, building..."
    echo "$choice" | "$SCRIPT_DIR"/build.sh
fi

# Set service user based on debug mode
if [[ "$CHOICE" == "$DEBUG_CHOICE" ]]; then
    SERVICE_USER="$PROJECT_NAME-debug"
else
    SERVICE_USER="$PROJECT_NAME"
fi

# First run the install.sh script
echo "$CHOICE" | "$SCRIPT_DIR"/install.sh

# Read directories from config file
INSTALL_DIR=$(get_install_directory "$BUILD_TYPE")
CONFIG_DIR="$INSTALL_DIR"

# Validate target user exists and has correct setup
if ! id "$SERVICE_USER" &>/dev/null; then
    echo "Error: $SERVICE_USER user does not exist"
    exit $ERROR_EXIT
fi

# Verify binary exists and is executable
if [[ ! -x "$INSTALL_DIR/$PROJECT_NAME" ]]; then
    echo "Error: Service binary not found or not executable at $INSTALL_DIR/$PROJECT_NAME"
    exit $ERROR_EXIT
fi

# Verify config file exists and has correct permissions
if [[ ! -f "$CONFIG_DIR/service.toml" ]]; then
    echo "Error: Config file not found at $CONFIG_DIR/service.toml"
    exit $ERROR_EXIT
fi

# Check config file permissions (should not be world-writable)
if [[ $(stat -c "%a" "$CONFIG_DIR/service.toml") -gt $CONFIG_FILE_PERMISSIONS ]]; then
    echo "Error: Config file has insecure permissions"
    exit $ERROR_EXIT
fi

# Run the program with validated user
echo "Starting service..."
sudo -u "$SERVICE_USER" "$INSTALL_DIR/$PROJECT_NAME"
