#!/bin/bash -e
################################################################
#
#  Name: Security Checks
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/security-checks.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  Runs Rust security audits and dependency vulnerability checks
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################

# Note: This script does not use SCRIPTS_DIR or source functions because it only
# runs standalone cargo commands and doesn't reference other files. It is only
# ever run in debug mode on the code in this repository.

echo "Running Rust Security Checks"
echo "============================"

# Exit on any error
set -e

echo "1. Security audit..."
cargo audit || echo "Warning: cargo audit failed or not installed"

echo "2. Unused dependencies check..."
cargo machete || cargo +nightly udeps || echo "Warning: unused dependency tools not available"

echo "3. Supply chain security..."
cargo deny check || echo "Warning: cargo deny not installed"

echo "All security checks completed!"
