#!/bin/bash -e
################################################################
#
#  Name: Update Scripts
#  GitHub repository: https://github.com/2ndSightLab/aws-scripts
#  File: scripts/update_scripts.sh
#  Copyright: © 2025 2nd Sight Lab, LLC
# 
#  Copies latest scripts from rust-service template to current project
# 
#  This software, which includes components generated with the assistance of artificial
#  intelligence, is free for personal, educational, and non-profit use, provided that
#  the included copyright notice is retained in all copies or substantial portions of
#  the software. This license, however, does not grant permission for any commercial
#  use, which requires obtaining a separate commercial license from the author. The
#  software is provided "as is," without any warranty, and the author cannot be held
#  liable for any damages or claims arising from its use. By using this software,
#  all users acknowledge that any potentially uncopyrightable portions generated by
#  AI are governed by the terms of this license as part of the overall work.
# 
################################################################


# Set standard directory variables and source all functions
SCRIPTS_DIR="$(dirname "$(readlink -f "$0")")"
for FUNC in "$SCRIPTS_DIR/functions"/*.sh; do source "$FUNC"; done
PROJECT_DIR=$(get_project_dir)

# Define configuration constants
ERROR_EXIT=1

# Get rust_service_path from Cargo.toml
RUST_SERVICE_PATH=$(get_cargo_config_value "metadata" "rust_service_path")

if [[ -z "$RUST_SERVICE_PATH" ]]; then
    echo "Error: rust_service_path not found in Cargo.toml"
    exit $ERROR_EXIT
fi

RUST_SERVICE_FULL_PATH="$PROJECT_DIR/$RUST_SERVICE_PATH"

if [[ ! -d "$RUST_SERVICE_FULL_PATH" ]]; then
    echo "Error: rust-service directory not found at $RUST_SERVICE_FULL_PATH"
    exit $ERROR_EXIT
fi

# Copy scripts from rust-service to PROJECT_DIR
echo "Copying scripts from $RUST_SERVICE_FULL_PATH to $PROJECT_DIR..."
cp -r "$RUST_SERVICE_FULL_PATH/scripts" "$PROJECT_DIR/"

echo "Scripts copied successfully!"
